# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START cloudbuild_go_yaml]
# [START cloudbuild_go_test_yaml]
steps:
  # [START cloudbuild_go_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA', '.']
  # [END cloudbuild_go_image_yaml]
  
  # [START cloudbuild_go_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA']
  # [END cloudbuild_go_push_yaml]
  
  # [START cloudbuild_go_deploy_yaml]
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '${REPO_NAME}',
           '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA',
           '--region', 'europe-west1', '--platform', 'managed']
  # [END cloudbuild_go_deploy_yaml]
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '${REPO_NAME}',
           '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA',
           '--region', 'europe-west2', '--platform', 'managed']
  # [END cloudbuild_go_deploy_yaml]

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '${REPO_NAME}',
           '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA',
           '--region', 'europe-west3', '--platform', 'managed']
  # [END cloudbuild_go_deploy_yaml]

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '${REPO_NAME}',
           '--image=europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA',
           '--region', 'europe-west4', '--platform', 'managed']
  # [END cloudbuild_go_deploy_yaml]

  # Delete docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['artifacts', 'docker', 'images', 'delete',
          'europe-west3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA']

  # Delete old revisions
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['revisions', 'list', 
           '--filter="status.conditions.type:Active AND status.conditions.status:'False'" --format='value(metadata.name)'',
           ' | xargs -r -L1 gcloud run revisions delete --quiet']

  # Deploy to Cloud Run
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', '${REPO_NAME}',
  #          '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA',
  #          '--region', 'us-east4', '--platform', 'managed']
  # [END cloudbuild_go_deploy_yaml]

  # Deploy to Cloud Run
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', '${REPO_NAME}',
  #          '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME:$SHORT_SHA',
  #          '--region', 'asia-northeast1', '--platform', 'managed']
  # [END cloudbuild_go_deploy_yaml]