package repository

var (
	// SaleFieldNames is a map of sale field names
	SaleFieldNames = map[string][]string{
		"id":                           {"id"},
		"document_id":                  {"document_id"},
		"document_no":                  {"document_no"},
		"transaction_no":               {"transaction_no"},
		"document_date":                {"document_date"},
		"posting_date":                 {"posting_date"},
		"entry_date":                   {"entry_date"},
		"shipment_date":                {"shipment_date"},
		"store_id":                     {"store_id"},
		"currency_id":                  {"currency_id"},
		"total_discount":               {"total_discount"},
		"total_exclusive_vat":          {"total_exclusive_vat"},
		"total_vat":                    {"total_vat"},
		"total_inclusive_vat":          {"total_inclusive_vat"},
		"subtotal_exclusive_vat_lcy":   {"subtotal_exclusive_vat_lcy"},
		"total_discount_lcy":           {"total_discount_lcy"},
		"total_exclusive_vat_lcy":      {"total_exclusive_vat_lcy"},
		"total_vat_lcy":                {"total_vat_lcy"},
		"total_inclusive_vat_lcy":      {"total_inclusive_vat_lcy"},
		"project_id":                   {"project_id"},
		"department_id":                {"department_id"},
		"contract_id":                  {"contract_id"},
		"user_group_id":                {"user_group_id"},
		"customer_id":                  {"customer_id"},
		"salesperson_id":               {"salesperson_id"},
		"responsibility_center_id":     {"responsibility_center_id"},
		"payment_terms_id":             {"payment_terms_id"},
		"payment_method_id":            {"payment_method_id"},
		"transaction_type_id":          {"transaction_type_id"},
		"payment_discount":             {"payment_discount"},
		"shipment_method_id":           {"shipment_method_id"},
		"payment_reference":            {"payment_reference"},
		"transaction_specification_id": {"transaction_specification_id"},
		"transport_method_id":          {"transport_method_id"},
		"exit_point_id":                {"exit_point_id"},
		"campaign_id":                  {"campaign_id"},
		"area_id":                      {"area_id"},
		"package_tracking_no":          {"package_tracking_no"},
		"agent_id":                     {"agent_id"},
		"agent_service_id":             {"agent_service_id"},
		"status":                       {"status"},

		// need to insert, not in treegrid cols
		"currency_value":          {"currency_value"},
		"direct_debit_mandate_id": {"direct_debit_mandate_id"},
		"subtotal_exclusive_vat":  {"subtotal_exclusive_vat"},
		"discount_id":             {"discount_id"},
	}

	// SaleLineFieldNames is a map of sale line field names
	SaleLineFieldNames = map[string][]string{
		"id-line":                {"sale_lines.id"},
		"Parent":                 {"parent_id"},
		"item_id":                {"item_id"},
		"item_type":              {"item_type"},
		"location_id":            {"location_id"},
		"input_quantity":         {"input_quantity"},
		"item_unit_id":           {"item_unit_id"},
		"tax_area_id":            {"tax_area_id"},
		"vat_id":                 {"vat_id"},
		"discount_id":            {"discount_id"},
		"subtotal_exclusive_vat": {"subtotal_exclusive_vat"},
		"total_discount":         {"total_discount"},
		"total_inclusive_vat":    {"total_inclusive_vat"},

		// need to insert, not in treegrid cols
		"item_unit_value":            {"item_unit_value"},
		"quantity":                   {"quantity"},
		"quantity_assign":            {"quantity_assign"},
		"quantity_assigned":          {"quantity_assigned"},
		"total_exclusive_vat":        {"total_exclusive_vat"},
		"total_vat":                  {"total_vat"},
		"subtotal_exclusive_vat_lcy": {"subtotal_exclusive_vat_lcy"},
		"total_discount_lcy":         {"total_discount_lcy"},
		"total_exclusive_vat_lcy":    {"total_exclusive_vat_lcy"},
		"total_vat_lcy":              {"total_vat_lcy"},
		"total_inclusive_vat_lcy":    {"total_inclusive_vat_lcy"},
	}
)
